#!/bin/sh

#NOTE: you can also call 
#      /usr/local/ec2onrails/bin/exec_runner
#      to run a script under a specific role
#      see the file for details

if test -e /mnt/app/current; then
  cd /mnt/app/current

  if test -e /mnt/app/current/script/cron/daily; then 
     if test -f /mnt/app/current/script/cron/daily; then 
        sudo -u app /usr/local/ec2onrails/bin/rails_env script/cron/daily;
     else 
        sudo -u app /usr/local/ec2onrails/bin/rails_env script/cron/daily/*;
     fi
     exit 0;
  fi

  #DEPRECATED: just for old usage....
  if test -e /mnt/app/current/script/daily
  then 
     sudo -u app /usr/local/ec2onrails/bin/rails_env script/daily
     exit 0;
  fi

fi
