#!/bin/sh

RAILS_ENV=`/usr/local/ec2onrails/bin/rails_env`

if [ -x /mnt/app/current ] ; then
  logfile=/mnt/app/current/log/$RAILS_ENV.log-`date +%Y%m%d`
  gzip $logfile
  /usr/local/ec2onrails/bin/archive_file.rb --file $logfile.gz --dir logs/rails && rm $logfile.gz
fi

for f in `ls /mnt/log/apache2/*.log` ; do
  logfile=$f-`date +%Y%m%d`
  gzip $logfile
  /usr/local/ec2onrails/bin/archive_file.rb --file $logfile.gz --dir logs/apache && rm $logfile.gz
done
