#!/bin/sh

#NOTE: you can also call 
#      /usr/local/ec2onrails/bin/exec_runner
#      to run a script under a specific role
#      see the file for details


cd /mnt/app/current

if test -e /mnt/app/current/script/cron/hourly
then 
   sudo -u app /usr/local/ec2onrails/bin/rails_env script/cron/hourly
   exit 0;
fi

#DEPRECATED: just for old usage....
if test -e /mnt/app/current/script/hourly
then 
   sudo -u app /usr/local/ec2onrails/bin/rails_env script/hourly
   exit 0;
fi
