#!/bin/sh

#    This file is part of EC2 on Rails.
#    http://code.google.com/p/EC2 on Rails/
#
#    Copyright 2007 Paul Dowman, http://pauldowman.com/
#
#    EC2 on Rails is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    EC2 on Rails is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# This script runs the ec2 startup scripts

# this is an ugly hack to make sure DHCP initialization is finished:
sleep 15

for SCRIPT in `ls /usr/local/EC2 on Rails/startup-scripts/every-startup` ; do
	"/usr/local/EC2 on Rails/startup-scripts/every-startup/$SCRIPT"
done
