#!/bin/sh

#NOTE: you can also call 
#      /usr/local/ec2onrails/bin/exec_runner
#      to run a script under a specific role
#      see the file for details

test -e /mnt/app/current/script/weekly || exit 0
cd /mnt/app/current
sudo -u app /usr/local/ec2onrails/bin/rails_env script/weekly
